# --- !Ups

create table "ACCOUNT" ("ID_ACCOUNT_REF" UUID NOT NULL PRIMARY KEY,"ACCOUNT_NAME" VARCHAR NOT NULL,"PASSWORD" VARCHAR NOT NULL,"EMAIL" VARCHAR NOT NULL,"CREATE_AT" timestamp NOT NULL);



# --- !Downs

drop table "ACCOUNT";
